### ISSUE TITLE
Update spark package against 1.6

### ISSUE THREAD

**Issue by slopp** [saurfang/spark-knn#14]
Can you re-publish the package to be built against Spark 1.6 ? We'd like to expose knn to sparklyr.

**Comment by preetpuri** [comment]
+1
we would like to use it too with Spark1.6

**Comment by palicand** [comment]
Actually, Spark 2.0 came out, so it would be nice to think about that as well :-)

**Comment by saurfang** [comment]
0.1.1 has been release which is compiled against 1.6. Feel free to test and let me know if you find any issues.
