### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by nesrineZibani** [saurfang/spark-knn#35]
when I try to run the test I get this error :

TypeError                                 Traceback (most recent call last)
<ipython-input-17-2e4268faf983> in <module>()
      3 
      4 
----> 5 knn = KNNClassifier(k=1, topTreeSize=1, topTreeLeafSize=1, subTreeLeafSize=1, bufferSizeSampleSize=[1, 2, 3])  # bufferSize=-1.0,
      6 model = knn.fit(training_data)
      7 

C:\spark-2.2.1-bin-hadoop2.7\python\pyspark\__init__.pyc in wrapper(self, *args, **kwargs)
    102             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    103         self._input_kwargs = kwargs
--> 104         return func(self, **kwargs)
    105     return wrapper
    106 

C:\spark-2.2.1-bin-hadoop2.7\python\pyspark\ml\knn.py in __init__(self, featuresCol, labelCol, predictionCol, seed, topTreeSize, topTreeLeafSize, subTreeLeafSize, bufferSize, bufferSizeSampleSize, balanceThreshold, k, neighborsCol, maxNeighbors, rawPredictionCol, probabilityCol)
     17         super(KNNClassifier, self).__init__()
     18         self._java_obj = self._new_java_obj(
---> 19             "org.apache.spark.ml.knn.KNNClassifier", self.uid)
     20 
     21         self.topTreeSize = Param(self, "topTreeSize", "number of points to sample for top-level tree")

C:\spark-2.2.1-bin-hadoop2.7\python\pyspark\ml\wrapper.pyc in _new_java_obj(java_class, *args)
     61             java_obj = getattr(java_obj, name)
     62         java_args = [_py2java(sc, arg) for arg in args]
---> 63         return java_obj(*java_args)
     64 
     65     @staticmethod

TypeError: 'JavaPackage' object is not callable

**Comment by kaushikacharya** [comment]
Hi,
  Have a look at the discussion in
https://github.com/saurfang/spark-knn/issues/32
Its probably because you are not using spark version: 2.1.0
