### ISSUE TITLE
Problem with example

### ISSUE THREAD

**Issue by josemarialuna** [saurfang/spark-knn#4]
Hi!
I've been studying your work but I have a problem with the example that you show in the main Readme.
It throws me a compiation error in toDF() method:
val training = MLUtils.loadLibSVMFile(sc, "data/mllib/sample_libsvm_data.txt").toDF()

And it also throws compilation errors in the last two lines, in the fit and transform methods, with the same reason.

Could you take a look?
Thx

**Comment by saurfang** [comment]
I took these example lines from ML documentation: http://spark.apache.org/docs/latest/ml-guide.html#example-model-selection-via-train-validation-split

I think what you probably need is to import MLUtils and also the implicits from sqlContext 
https://github.com/saurfang/spark-knn/blob/master/spark-knn-examples/src/main/scala/com/github/saurfang/spark/ml/knn/examples/MNIST.scala#L17
