### ISSUE TITLE
A point is considered its' own neighbour

### ISSUE THREAD

**Issue by palicand** [saurfang/spark-knn#7]
Hello,

I have noticed a weird behaviour. For some reason, the algorithm counts each point as its' own neighbour, i. e. when using KNN(1), the only neighbour the algorithm finds is the point itself. Can some bad setting of a parameter cause this? Or is it a *"feature"*?

**Comment by saurfang** [comment]
That's a design choice. Say we have three points with the same feature vector but label 0, 0 and 1. The two points with the same label would seem to be identical but all three can in fact be different points. There is no unique identifier that differentiates each point. I realize in the program itself the "identical" concept does exist but in the general sense, I feel this introduces unnecessary complication in implementation.
